version: 2
sources:
    - name: snowflake_data
      database: "{{('DEV_RAW')}}"
      schema: AMAZON
      tables:
        - name: LINEITEM
          columns:
            - name: l_orderkey
              tests:
                - not_null
            - name: l_quantity
              tests:
                - not_null
            - name: l_linenumber
              tests:
                - not_null  
        - name: NATION
          columns:
            - name: n_nationkey
              tests:
                - unique
                - not_null
            - name: n_name
              tests:
                - not_null
        - name: ORDERS
          columns:
            - name: o_orderkey
              tests:
               - unique
               - not_null

        - name: CUSTOMERS 
          columns:
           - name: c_custkey
             tests:
              - unique
              - not_null
           - name: c_name
             tests:
               - not_null
        - name: RAW_SUPPLIER
        - name: RAW_PARTSUPP
        - name: RAW_PART
        - name : RAW_REGION
        - name : RAW_CUSTOMER_NATION
 
    - name: snapshot_tables
      database: "{{('DEV_MART')}}"
      schema: AMAZON
      tables:
        - name: snap_ordersdetails
